Iss476
JeffersonLab/hps-java pull request #1015
Opened 2023-10-19 16:34 UTC by bloodyyugo

This should be all set with killing L1 strip clusters-on-track for MC based on the track slope for both GBL and KF tracks.  Included are steering files for 2016.  

Also included with this push is code to kill (per sensor) strip clusters based on the actual positions on the sensor (StripHitKiller.java) based off of the driver org.hps.svt.SVTHitLevelPlots.java.  No warrantee expressed or implied for this code though.  My next next push will include updated  SVTHitLevelPlots-like drivers for both GBL and Kalman tracks, along with (hopefully) changes to the code that implements killing based on these that gives reasonable results.

2024-01-23 08:49 UTC, pbutti approved these changes

2024-01-23 21:56 UTC, sarahgaiser requested changes

2024-01-23 21:56 UTC, sarahgaiser commented on steering-files/src/main/resources/org/hps/steering/analysis/SVTHitPlots.lcsim
> +<<<<<<< HEAD
left over git markers should be cleaned up

2024-01-23 21:56 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/kalman/SvtHitEfficiencyKalman.java
> +    Map<String, IHistogram2D> errorUvsPPos = new HashMap<String, IHistogram2D>();
Is this bif section of things that are commented out still needed? if not, we could remove it?

2024-01-23 21:56 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/kalman/SvtHitEfficiencyKalman.java
> +                /*
Same here, do we need to keep it?

2024-01-23 21:59 UTC, sarahgaiser commented
I didn't have time to review this in detail yet, but from a first glance, it would be nice to work on the formatting and to possibly refactor some of the super big `.java` files so that they are not >1000 lines long. That's a quite some added work though.

2024-01-24 18:33 UTC, sarahgaiser requested changes

2024-01-24 18:33 UTC, sarahgaiser commented on steering-files/src/main/resources/org/hps/steering/analysis/PhysicsRun2016SVTHitEffKalman.lcsim
> +      @brief Steering file that will be used for pass 1 reconstruction of
Is this still up to date?

2024-01-24 18:33 UTC, sarahgaiser commented on steering-files/src/main/resources/org/hps/steering/analysis/PhysicsRun2016SVTHitEffKalman.lcsim
> +      @brief Steering file that will be used for pass 1 reconstruction of
If not, maybe we can add so description here?

2024-01-24 18:33 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +            for (SensorToKill sensorToKill : _sensorsToKill)
is this missing the {} brackets around the part that we should loop over?

2024-01-25 16:52 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/kalman/SvtHitEfficiencyKalman.java
> +    Map<String, IHistogram1D> numberOfTracksChannelCorrected = new HashMap<String, IHistogram1D>();
is this section going to be relevant at some time or will it stay as a comment forever?

2024-01-25 17:03 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +            for (SensorToKill sensorToKill : _sensorsToKill)
I guess it also works without because it's just looping over the if statement? anyway, adding the brackets would make it easier to read

2024-01-25 18:37 UTC, sarahgaiser requested changes

2024-01-25 18:37 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +                    //                    List<TrackerHit> stripsToKill=getTrackHitsPerModule(trk,hitToStrips,hitToRotated,modToKill.getLayer());
is this comment needed?

2024-01-25 18:37 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +        int flag = LCIOUtil.bitSet(0, 31, true); // Turn on 64-bit cell ID.
this flag is unused

2024-01-25 18:37 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private Map<Track,Double> getUniqueTracksFromV0List(List<ReconstructedParticle> unconstrainedV0List){
This function is defined again in KalmanSlopeBasedTrackHitKiller and both are exactly the same.

2024-01-25 18:37 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private double correctSlope(double z,double slp){
correctSlope and layerToModule are also defined twice in the exact same way.

2024-01-25 18:37 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private Map<Track,Double> getUniqueTracksFromV0List(List<ReconstructedParticle> unconstrainedV0List){
I would add a level of abstraction here and create a mother class with shared functionality. Maybe SlopeBasedTrackHitKiller could also be the mother class and KalmanSlopeBasedTrackHitKiller is the daughter.

2024-01-25 18:47 UTC, sarahgaiser requested changes

2024-01-25 18:47 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private final String helicalTrackHitRelationsCollectionName = "HelicalTrackHitRelations";
`helicalTrackHitCollectionName` and `rotatedTrackHitCollectionName` are unused

2024-01-25 18:47 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private Map<TrackerHit, Boolean> _siClustersAcceptMap = new HashMap<TrackerHit, Boolean>();
`_siClustersAcceptMap` and `_finalSiClustersAcceptMap` are unused

2024-01-25 18:47 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/KalmanSlopeBasedTrackHitKiller.java
> +    private Map<TrackerHit, Boolean> _siClustersAcceptMap = new HashMap<TrackerHit, Boolean>();
`_siClustersAcceptMap` and `_finalSiClustersAcceptMap` are unused

2024-01-29 17:59 UTC, sarahgaiser requested changes

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    public void detectorChanged(Detector detector) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    public void registerSensor(int layer, boolean isTop, boolean isStereo, boolean isSlot, String ratioFile) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private HpsSiSensor getSensor(int layer, boolean isTop, boolean isAxial, boolean isHole) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private List<TrackerHit> getFinalHits(Map<TrackerHit, Boolean> _initialSiClustersAcceptMap) {
not used

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private double getSmearedRatio(int seedChan, SensorToKill sensorToKill) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private Map<Integer, Double> fillSmearedFractions(double sigmaU, int layer) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    public class SensorToKill {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private Hep3Vector toHep3(double[] arr) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private int getChan(Hep3Vector pos, HpsSiSensor sensor) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private Hep3Vector globalToSensor(Hep3Vector trkpos, HpsSiSensor sensor) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private double computeGaussInt(double nSig, int nSteps) {
same as in StripHitKiller

2024-01-29 17:59 UTC, sarahgaiser commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    private double Gauss(double x, double mean, double sigma) {
same as in StripHitKiller

2024-01-30 00:12 UTC, bloodyyugo commented on tracking/src/main/java/org/hps/recon/tracking/TrackHitKiller.java
> +    public void detectorChanged(Detector detector) {
removed this driver..

2024-01-30 00:14 UTC, bloodyyugo commented on tracking/src/main/java/org/hps/recon/tracking/SlopeBasedTrackHitKiller.java
> +    private Map<Track,Double> getUniqueTracksFromV0List(List<ReconstructedParticle> unconstrainedV0List){
I used SlopeBasedTrackHitKiller to extend KalmanSlopeBasedTrackHitKiller and removed the redundent code

2024-01-30 17:04 UTC, sarahgaiser approved these changes

2024-01-30 22:26 UTC, merged