Add some checks in SimpleGBLTrajAliDriver  etc
JeffersonLab/hps-java pull request #1038
Opened 2024-05-16 16:50 UTC by bloodyyugo

In SimpleGBLTrajAliDriver:  
Add a check that trackGblStripClusterData is filled. 
Checks that global derivatives don't contain a NaN. 

In GBLOutputDriver:
Change range on Chi2oNDF so that details can be seen

2024-05-17 09:16 UTC, pbutti requested changes

2024-05-17 09:16 UTC, pbutti commented on tracking/src/main/java/org/hps/recon/tracking/gbl/SimpleGBLTrajAliDriver.java
> +		System.out.println("SimpleGBLTrajAliDriver::trackGblStripClusterData is null, skipping track");
@bloodyyugo
Remove println, or put it under debug pls.

2024-05-17 09:16 UTC, pbutti commented on tracking/src/main/java/org/hps/recon/tracking/gbl/SimpleGBLTrajAliDriver.java
> +			    System.out.println("SimpleGBLTrajAli::ComputeStructureDerivatives globals derivatives probably have NaN");
Remove println or put it under debug

2024-05-17 09:16 UTC, pbutti commented on tracking/src/main/java/org/hps/recon/tracking/gbl/SimpleGBLTrajAliDriver.java
> +			    System.out.println("SimpleGBLTrajAli::ComputeCOMDerivatives globals derivatives probably have NaN");
Remove println or put it under debug

2024-09-18 23:21 UTC, cbravo135 commented
detector.properties has not been updated properly for most of these detectors. Not sure we want to add every iteration you did while aligning to the master branch. We should chat about what all from this PR we want to include.

2024-12-13 21:22 UTC, closed without merging