Iss659
JeffersonLab/hps-java pull request #665
Opened 2020-03-05 20:31 UTC by pbutti

Details in 
https://github.com/JeffersonLab/hps-java/issues/659

2020-03-08 17:04 UTC, mholtrop requested changes
See other comments.
Please make sure that the code in this issue is actually the code that you have been testing. It currently does not seem to be correct, so there may be other files that are different between what is in the repo for this issue and what you have been working with.

2020-03-08 17:04 UTC, mholtrop commented on analysis/src/main/java/org/hps/analysis/MC/TrackToMCParticleRelationsDriver.java
> +            }
The three lines above give a "check style violation" for incorrect indentation.
Note a big deal, but it does prevent the tests from running.

2020-03-08 17:04 UTC, mholtrop commented on analysis/src/main/java/org/hps/analysis/MC/TrackToMCParticleRelationsDriver.java
> +                        System.out.printf("d0 %f z0 %f R %f phi %f lambda %s\n", trk_htf.dca(), trk_htf.z0(), trk_htf.R(), trk_htf.phi0(), trk_htf.slope());
try_htf does not seem to have been defined yet at this point.

2020-03-10 02:24 UTC, pbutti commented
Thanks @mholtrop ,
for checking this. Uhm.. Weird that there are these errors as locally seems to work fine. I ported additional fixes from Robert, so I'll open a new merge request with the updated branch and check these issues.

2020-03-10 02:24 UTC, closed without merging