Iss872
JeffersonLab/hps-java pull request #874
Opened 2021-06-03 23:05 UTC by normangraf

In cases where the APV25 waveform is fit to two pulses, this code only saves the fit whose time is closer to t=0.
Additionally, all fits with times less than a settable time _minT0_ or greater than a settable time _maxT0_ can be dropped by setting _dropOutOfTimeFits_ in the steering file.

This pull request produces some differences to three of the integration test plots, so will require the reference plots to be updated. 

Failed tests:
  EngRun2015V0ReconTest>ReconTest.testRecon:380->ReconTest.comparePlots:252->ReconTest.compareTrees:272->ReconTest.compareHistograms:293 Bin 99 is different for: V0 Vertex x expected:<63> but was:<64>
  PhysRun2016MollerReconTest>ReconTest.testRecon:380->ReconTest.comparePlots:252->ReconTest.compareTrees:272->ReconTest.compareHistograms:293 Bin 61 is different for: Moller Bottom Track Momentum expected:<119> but was:<118>
  PhysRun2016V0ReconTest>ReconTest.testRecon:380->ReconTest.comparePlots:252->ReconTest.compareTrees:272->ReconTest.compareHistograms:293 Bin 66 is different for: V0 Track Chisq Prob expected:<89> but was:<90>

2021-06-03 23:54 UTC, cbravo135 requested changes
As written this code change will always remove the pulse further from zero when two exist, and the old behavior is not possible. This has not been agreed on at any meeting, so the default should be the old behavior, which currently is not even possible. This explains why the tests are failing. Please make the code default to the old behavior of keeping both pulses when two pulses are fit to a waveform. It was actually discussed that more studies need to be done before considering the behavior this code explicitly forces.

2021-06-04 00:52 UTC, bloodyyugo commented
I'm a little hesitant to put a stopgap in now when we should just spend the effort to do this right.  By "right" I mean either fix the relations so that we can get both fits from the raw hit (and then decide in tracking) or we look at the other fit parameters (amplitude, uncertainties?) to help figure out which hit to keep (although, probably these will prefer the in-time hit).  I'm also afraid that these two-pulse hits aren't very good to begin with, but I'd like to keep that info (that they are two-pulse instead of one-pulse) somewhere where we can get it in analysis.  I don't think we are doing that now.

2021-06-04 02:44 UTC, cbravo135 commented
As the code is currently, we do keep both pulse fits. No fix is needed to access them during tracking.

2021-06-04 03:42 UTC, cbravo135 commented
A more flexible solution would be to add a driver to filter them before tracking.

2021-06-04 21:28 UTC, normangraf commented
This change was discussed at length in at least two presentations ([part 1](https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=311544084&preview=/311544084/311544674/20210525_SVTHitAnalysis_ReconMeeting_Graf.pdf)[part 2](https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=311544084&preview=/311544084/311544682/20210525_SVTHitAnalysisII_ReconMeeting_Graf.pdf) ) These changes were specifically proposed and no objections were raised at the time.

2021-06-04 23:32 UTC, normangraf commented
> I'm a little hesitant to put a stopgap in now when we should just spend the effort to do this right. By "right" I mean either fix the relations so that we can get both fits from the raw hit (and then decide in tracking) or we look at the other fit parameters (amplitude, uncertainties?) to help figure out which hit to keep (although, probably these will prefer the in-time hit). I'm also afraid that these two-pulse hits aren't very good to begin with, but I'd like to keep that info (that they are two-pulse instead of one-pulse) somewhere where we can get it in analysis. I don't think we are doing that now.

I drop poor hits, keep all the good hits, don't lose any tracks, speed up the reconstruction and make the output file size smaller. Calling this a "stopgap" trivializes the amount of work I have put into analyzing this issue and ensuring that the changes to the code do not result in any appreciable changes in our "good" events. No tracks were lost in either the 2016 Møller or V0 integration tests and at most a few tracks changed slightly (and perhaps even for the better). For your convenience the comparison plots for the 2016 V0 integration test can be found in the attached file.  
[plots.pdf](https://github.com/JeffersonLab/hps-java/files/6601639/plots.pdf)

2021-06-06 19:00 UTC, cbravo135 commented
Objections to this were raised during both presentations cited. During the referenced discussions we agreed that we would like to further study the errors we gain to the hit times before making any decision about how to filter the events. We also did not discuss implementation details, and this code forces the proposed behavior while not allowing the current behavior. A consensus has not been made about this proposal and follow up studies were requested to further understand the ramifications of this change.

2021-06-06 19:02 UTC, cbravo135 commented
It has not been demonstrated that this will "keep all good hits", and plots in the presentations cited suggest (but do not establish) that some good hits are dropped. A definition of a "good hit" has not been established in an attempt to quantify this.

2021-06-07 15:37 UTC, mholtrop approved these changes
Difference in the integration tests are completely minimal. We have approved changes with far larger differences without any fuss. This project was well discussed and presented at the software meeting, and this does not seem a stop-gap fix. 
There seems to me to be no reason to add complexity so that someone can restore the old faulty behavior. If you want that, you can just get the old version of the driver.

2021-06-07 18:24 UTC, cbravo135 commented
The integration tests use highly skimmed data for clean events from 2016 and 2015. The tracking used is seed tracker. The discussion during the meeting indicated that we were first interested in studying the cases when two pulses are used and possibly one one really should be used. There is no reason this requirement must be in this driver, and for future studies it would be easier for this filtering to happen in a driver after this so the pulse fitting can still be studied fully after running. Tracks should be studied using the planned 2019 reconstruction configuration using a run that is not during the pulsed beam saga. The second set of slides is exclusively looking at a run that is not representative of running conditions for over 80% of our 2019 data.

2021-06-07 18:35 UTC, normangraf commented
This is a pull **request**.  I've demonstrated that we don't lose any "good" events, as previously defined, and the only changes over thousands of events was a slight change in the track chi-squared of a few tracks. Please feel free to proceed with your own studies to define what a "good hit" should be and to process representative runs in order to study the cases when two pulses are used and possibly only one really should be used.

2021-06-07 19:06 UTC, cbravo135 commented
You have not attempted demonstrate we do not lose any good events in any way it could be defined in 2019, since you have not checked 2019 tracking using this code.

2021-06-08 06:05 UTC, normangraf commented
All of the plots in both of my presentations are from 2019 data. I did not "analyze" any 2015 or 2016 data until I ran the integration tests.

2021-06-08 18:04 UTC, cbravo135 commented
You used run 10515 which is a run in 2019 with a known issue that is only present in about 12% of the 2019 data. It is not representative of the conditions of the 2019 run.

2021-06-09 03:31 UTC, normangraf commented
Please see my presentation at the June 8, 2021 analysis meeting:
https://confluence.slac.stanford.edu/display/hpsg/June+8%2C+2021+Meeting?preview=/311553517/311553773/20210608_SVTHitAnalysisIII_AnalysisMeeting_Graf.pdf
I've now shown that there is no loss of tracks when implementing this change in the 2015 & 2016 integration tests and in a sensitive three-prong trident analysis of the 2019 data spanning all runs. In addition, of the few tracks which are changed, the changes are minimal.

2021-06-09 16:23 UTC, cbravo135 commented
This presentation does not describe the selection used for the three prong-tridents. I notice the rate of these are rather low. If we are going to force the behavior to be to drop one of the fits, there should be an independent check on a less cherry picked selection of events. "No loss of tracks" is too strong of a claim for what is presented in those slides.

2021-06-09 18:08 UTC, normangraf commented
Please proceed with your independent check. We can discuss it at the next analysis or reconstruction meeting.

2021-06-10 01:40 UTC, cbravo135 commented
Please provide the provenance and details of the selection for the analysis used in https://confluence.slac.stanford.edu/display/hpsg/June+8%2C+2021+Meeting?preview=/311553517/311553773/20210608_SVTHitAnalysisIII_AnalysisMeeting_Graf.pdf

2021-06-11 01:54 UTC, cbravo135 commented
After digging a bit more, it turns out that dropping the fit further from t0 = 0 is already done in the clustering algorithm: 
https://github.com/JeffersonLab/hps-java/blob/master/tracking/src/main/java/org/hps/recon/tracking/NearestNeighborRMSClusterer.java#L137

This is why there is no change in tracking, because this cut here would not be expected to produce any different set of clusters. This only makes it more cumbersome to study the pile up fitting.

2021-06-11 04:18 UTC, normangraf commented
> After digging a bit more, it turns out that dropping the fit further from t0 = 0 is already done in the clustering algorithm:

Yes, indeed! And if you look closely you will notice that the out-of-time strip clusters are dropped as well, which is why I also added the ability to drop out of time fits. That is the whole point of this issue: to drop fits that will in any case never be used. By "failing early" it reduces both the processing time and the output file size without affecting the results in any appreciable way.

Please remove your block so we can proceed to the next stage of data reconstruction.

2021-06-11 04:31 UTC, cbravo135 commented
This is not needed for the next stage of data reconstruction. It has not been demonstrated this gains us an appreciable amount of time or disk space. This will lose information about the fits performed so we can analyze them and work to improve the decisions about when to use one fit or two fits. When both fits are within 50 ns, we should consider adding the amplitudes during clustering if unable to remove all the fits when the second pulse is ahead in time.

2021-06-11 04:37 UTC, cbravo135 commented
Currently the out of time cluster window is 144 ns wide, so we aren't dropping that many fits that way: https://confluence.slac.stanford.edu/display/hpsg/June+8%2C+2021+Meeting?preview=/311553517/311556300/anaMeet210608.pdf

2021-06-11 04:40 UTC, cbravo135 commented
Please make it configurable so our collaborators can study the hit fit time errors we recently started using migrad to get.

2021-06-11 04:45 UTC, cbravo135 commented
This PR as is loses information that could be analyzed by the SVT group, and has not been shown to gain anything appreciable.

2021-06-11 05:09 UTC, pbutti commented
Hi All, 
I don't fully understand why this is so controversial, but perhaps would be agreeable to use a flag that can be switched from steering files to activate Norman's selection of the fitted T0? 
I don't have anything against this PR, but if we want to keep things open for further study, and not everyone feels comfortable with this change, why not adding a boolean flag for activation at this stage?

2021-06-11 06:53 UTC, cbravo135 commented
It is not true that this PR only "drop fits that will in any case never be used." as claimed by @normangraf in his last comment. Hit fits with a time of -70 ns would be dropped whereas they are currently used by code that runs after this in all current steering files with reconstruction of SVT clusters. @normangraf claimed "That is the whole point of this issue: to drop fits that will in any case never be used." and this PR is outside the scope of that claim.

2021-06-16 17:12 UTC, bloodyyugo commented
I agree with PF...let's add a flag so that this can be enabled/disabled via steering file and then I'm fine signing off.

2021-06-16 17:14 UTC, normangraf commented
That's a lot of extra work.
And I'm sure Cameron will argue to turn the switch off.

________________________________
From: Matt Graham ***@***.***>
Sent: Wednesday, June 16, 2021 10:12 AM
To: JeffersonLab/hps-java ***@***.***>
Cc: Graf, Norman A. ***@***.***>; Mention ***@***.***>
Subject: Re: [JeffersonLab/hps-java] Iss872 (#874)


I agree with PF...let's add a flag so that this can be enabled/disabled via steering file and then I'm fine signing off.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/JeffersonLab/hps-java/pull/874#issuecomment-862559631>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADRGZDSVT45VPKGDVKASPZ3TTDLPTANCNFSM46BVQRUA>.

2021-06-16 17:18 UTC, bloodyyugo commented
I just looked at the code and you already have the setters there.  It look like you just have to add a line to the steering file.  We want to be able to turn this off to do studies of the two-hit pulses.

2021-08-02 16:58 UTC, bloodyyugo approved these changes
I'd prefer to see a switch in here that turns this on and off but since this change doesn't change any behavior in current code I guess it's ok.  We need to look into this more in the near future.

2021-08-02 17:13 UTC, normangraf commented
I agree that further study of the APV25 waveform fitting is merited. But I think the gains from this modification, especially since it does not change the results of our current reconstruction in any appreciable manner, warrant this update.

2021-09-08 19:21 UTC, cbravo135 commented
It has not been demonstrated that there are any gains from this change. This only removes information so it is not possible anymore to further study the APV25 waveform fitting.

2022-02-08 18:42 UTC, normangraf commented
Will not pursue.

2022-02-08 18:42 UTC, closed without merging